name: CI

on: [push, workflow_dispatch]

jobs:
  Test:
    runs-on: ubuntu-latest

    container:
      image: golang

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          make deps
          go test ./...
